### ISSUE TITLE
每次重启更新增加一条记录

### ISSUE THREAD

**Issue by ZHonry** [kylinfedora/bash_aliddns#1]
感谢你的脚本，让我可以在usg上直接用aliddns
这个脚本我只修改了这几个
aliddns_ak="LTAIupxxxxxxe6"
aliddns_sk="haSxvxFbUzzzzzzpaOWwlEe"
aliddns_curl="curl -s http://members.3322.org/dyndns/getip"
aliddns_dns="223.5.5.5"
aliddns_ttl="600"
aliddns_domain="hxx.net"
aliddns_name="*"
然后在每次重启USG的时候，都会直接新增一条记录，而不是直接更新原有的。

**Comment by ZHonry** [comment]
正常了，第一次更新增加后就没再增加过

**Comment by kylinfedora** [comment]
现在还有问题吗？

**Comment by crystalcamel** [comment]
> 现在还有问题吗？

非常感谢，网上的sh都解析不了@，帮了我很大的忙，再次感谢。
